(function(){'use strict';
const M=window.EmulsionMath, ids=['tankHeightCm','boxHeightCm','currentConcentrationPct','targetConcentrationPct'];
const $=id=>document.getElementById(id), br=(n,d=1)=>n.toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});
let config={...M.DEFAULT_CONFIG},history=[],calibrations=[],adaptiveEnabled=true,current=null,currentInputs=null,validationRecordId=null;
try{config={...config,...JSON.parse(localStorage.getItem('emulsao-config-v1')||'{}')};history=JSON.parse(localStorage.getItem('emulsao-history-v1')||'[]');calibrations=JSON.parse(localStorage.getItem('emulsao-calibrations-v1')||'[]');adaptiveEnabled=localStorage.getItem('emulsao-adaptive-enabled')!=='false'}catch{}
const specs=[['tankLengthM','Comprimento do tanque','m'],['tankWidthM','Largura do tanque','m'],['tankHeightCm','Altura útil do tanque','cm'],['boxCapacityLiters','Capacidade da caixa','L'],['boxHeightCm','Altura útil da caixa','cm'],['boxBottomDiameterM','Diâmetro inferior','m'],['boxTopDiameterM','Diâmetro superior','m'],['minConcentrationPct','Concentração mínima','%'],['maxConcentrationPct','Concentração máxima','%']];
function configUI(){ $('configFields').innerHTML=specs.map(([k,l,u])=>`<label>${l}<input data-config="${k}" type="number" min="0" step="0.01" value="${config[k]}"> ${u}</label>`).join('');$('tankHint').textContent=`Máximo ${config.tankHeightCm} cm`;$('boxHint').textContent=`Máximo ${config.boxHeightCm} cm`;document.querySelectorAll('[data-config]').forEach(el=>el.oninput=e=>{config[e.target.dataset.config]=Number(e.target.value);localStorage.setItem('emulsao-config-v1',JSON.stringify(config));configUIHints();calculate()})}
function configUIHints(){$('tankHint').textContent=`Máximo ${config.tankHeightCm} cm`;$('boxHint').textContent=`Máximo ${config.boxHeightCm} cm`}
function inputs(){return {...Object.fromEntries(ids.map(id=>[id,Number($(id).value.replace(',','.'))])),fixedAdditionalLiters:0}}
function calculate(){if(!$('tankHeightCm').value||!$('boxHeightCm').value||!$('currentConcentrationPct').value){$('empty').hidden=false;$('output').hidden=true;current=null;return}const i=inputs(),e=M.validateInputs(i,config);$('errors').hidden=!e.length;$('errors').textContent=e.join(' ');if(e.length){$('empty').hidden=false;$('output').hidden=true;current=null;return}const stats=M.calibrationStats(calibrations),factor=adaptiveEnabled?stats.appliedFactor:1;currentInputs=i;current=M.calculateAll(i,config,factor);$('empty').hidden=true;$('output').hidden=false;$('tankVolume').textContent=br(current.tankVolumeLiters)+' L';$('boxVolume').textContent=br(current.boxVolumeLiters)+' L';$('totalVolume').textContent=br(current.totalVolumeLiters)+' L';$('modelConfidence').textContent=adaptiveEnabled?stats.confidence:'APRENDIZADO DESATIVADO';$('modelFactor').textContent=`Fator × ${factor.toFixed(4).replace('.',',')}`;$('oilDose').textContent=br(current.oilToAddLiters);$('operationalDose').textContent=br(current.operationalOilLiters,0);const s=$('status');s.className='status '+(current.status==='DENTRO DA FAIXA'?'ok':current.status==='ABAIXO DA FAIXA'?'low':'high');s.querySelector('strong').textContent=current.status;const w=current.status==='ACIMA DA FAIXA';$('waterBox').hidden=!w;if(w)$('waterDose').textContent=`${br(current.waterToAddLiters)} L para retornar ao limite máximo de ${br(config.maxConcentrationPct,2)}%`}
ids.forEach(id=>$(id).addEventListener('input',calculate));
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab],.tabpage').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});
$('clear').onclick=()=>{ids.forEach(id=>$(id).value=id==='targetConcentrationPct'?'2.5':'');$('message').textContent='';calculate()};
$('resetConfig').onclick=()=>{config={...M.DEFAULT_CONFIG};localStorage.setItem('emulsao-config-v1',JSON.stringify(config));configUI();calculate()};
$('save').onclick=()=>{if(!current)return;history.unshift({...currentInputs,...current,id:(crypto.randomUUID?crypto.randomUUID():Date.now().toString()),timestamp:new Date().toISOString()});persist();$('message').textContent='Medição registrada. Após a correção, valide o resultado no Histórico.'};
function persist(){localStorage.setItem('emulsao-history-v1',JSON.stringify(history));localStorage.setItem('emulsao-calibrations-v1',JSON.stringify(calibrations));renderHistory();calculate()}
function renderHistory(){const stats=M.calibrationStats(calibrations);$('count').textContent=history.length;$('adaptiveEnabled').checked=adaptiveEnabled;$('learningSummary').textContent=stats.sampleCount?`${stats.sampleCount} validação(ões) · ${stats.confidence} · fator aplicado × ${stats.appliedFactor.toFixed(4).replace('.',',')}`:'Nenhuma validação pós-correção — usando somente o modelo geométrico';$('noHistory').hidden=!!history.length;$('historyBody').innerHTML=history.map(i=>{const c=calibrations.find(x=>x.recordId===i.id);return `<tr><td>${new Date(i.timestamp).toLocaleString('pt-BR')}</td><td>Tanque ${br(i.tankHeightCm)} · Caixa ${br(i.boxHeightCm)}</td><td>${br(i.currentConcentrationPct,2)}%</td><td>${br(i.totalVolumeLiters)} L</td><td><span class="badge ${i.status==='DENTRO DA FAIXA'?'ok':i.status==='ABAIXO DA FAIXA'?'low':'high'}">${i.status}</span></td><td>${br(i.oilToAddLiters)} L (${br(i.operationalOilLiters,0)} L op.)</td><td>${c?`<span class="validated">✓ ${br(c.afterConcentrationPct,2)}% · fator × ${c.factor.toFixed(4).replace('.',',')}</span>`:`<button class="validate" data-validate="${i.id}">Validar resultado</button>`}</td><td><button class="delete" data-delete="${i.id}" title="Excluir">✕</button></td></tr>`}).join('');document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{history=history.filter(i=>i.id!==b.dataset.delete);calibrations=calibrations.filter(c=>c.recordId!==b.dataset.delete);persist()});document.querySelectorAll('[data-validate]').forEach(b=>b.onclick=()=>openValidation(b.dataset.validate))}
function download(name,text,type){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
$('csv').onclick=()=>{const h=['data_hora','altura_tanque_cm','altura_caixa_cm','concentracao_atual_pct','concentracao_alvo_pct','volume_tanque_l','volume_caixa_l','volume_total_l','fator_usado','status','oleo_teorico_l','oleo_operacional_l','agua_teorica_l','oleo_real_l','concentracao_apos_pct','volume_observado_l','fator_observado'];const rows=history.map(i=>{const c=calibrations.find(x=>x.recordId===i.id)||{};return[i.timestamp,i.tankHeightCm,i.boxHeightCm,i.currentConcentrationPct,i.targetConcentrationPct,i.tankVolumeLiters,i.boxVolumeLiters,i.totalVolumeLiters,i.calibrationFactor||1,i.status,i.oilToAddLiters,i.operationalOilLiters,i.waterToAddLiters,c.actualOilLiters||'',c.afterConcentrationPct||'',c.observedVolumeLiters||'',c.factor||'']});download('historico_emulsao.csv','\uFEFF'+[h,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\r\n'),'text/csv;charset=utf-8')};
$('backup').onclick=()=>download('backup_controle_emulsao.json',JSON.stringify({version:2,config,history,calibrations,adaptiveEnabled},null,2),'application/json');$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(![1,2].includes(d.version)||!Array.isArray(d.history))throw 0;config={...M.DEFAULT_CONFIG,...d.config};history=d.history;calibrations=Array.isArray(d.calibrations)?d.calibrations:[];adaptiveEnabled=d.adaptiveEnabled!==false;localStorage.setItem('emulsao-config-v1',JSON.stringify(config));persist();configUI();alert('Backup importado com sucesso.')}catch{alert('Arquivo de backup inválido.')}};
function openValidation(id){const r=history.find(i=>i.id===id);if(!r)return;validationRecordId=id;$('validationRecord').textContent=`Medição inicial: ${br(r.currentConcentrationPct,2)}% · volume previsto ${br(r.totalVolumeLiters)} L`;$('actualOil').value=r.operationalOilLiters||r.oilToAddLiters||'';$('afterConcentration').value='';$('validationError').hidden=true;$('validationDialog').showModal()}
$('saveValidation').onclick=()=>{const r=history.find(i=>i.id===validationRecordId),oil=Number($('actualOil').value),after=Number($('afterConcentration').value),observed=r&&M.inferObservedVolumeFromOil(oil,r.currentConcentrationPct,after);if(!r||!observed){$('validationError').hidden=false;$('validationError').textContent='A concentração final deve ser maior que a inicial e o óleo real deve ser maior que zero. Não use esta validação se houve retirada de solução ou adição de água.';return}const geometric=r.geometricVolumeLiters||r.tankVolumeLiters+r.boxVolumeLiters,factor=observed/geometric;calibrations=calibrations.filter(c=>c.recordId!==r.id);calibrations.push({recordId:r.id,timestamp:new Date().toISOString(),actualOilLiters:oil,beforeConcentrationPct:r.currentConcentrationPct,afterConcentrationPct:after,observedVolumeLiters:observed,geometricVolumeLiters:geometric,factor});persist();$('validationDialog').close()};
$('adaptiveEnabled').onchange=e=>{adaptiveEnabled=e.target.checked;localStorage.setItem('emulsao-adaptive-enabled',String(adaptiveEnabled));persist()};$('resetLearning').onclick=()=>{if(confirm('Apagar todas as validações usadas pelo modelo adaptativo?')){calibrations=[];persist()}};
let technicalUnlocked=sessionStorage.getItem('emulsao-tech-unlocked')==='true';$('technicalDetails').querySelector('summary').onclick=e=>{if(!technicalUnlocked){e.preventDefault();const password=prompt('Digite a senha para acessar os parâmetros técnicos:');if(password==='processo'){technicalUnlocked=true;sessionStorage.setItem('emulsao-tech-unlocked','true');$('technicalDetails').open=true}else if(password!==null)alert('Senha incorreta.')}};$('lockConfig').onclick=()=>{technicalUnlocked=false;sessionStorage.removeItem('emulsao-tech-unlocked');$('technicalDetails').open=false};
// Módulo independente de decapagem.
let dConfig={...M.DEFAULT_PICKLING_CONFIG},dHistory=[],dCalibrations=[],dAdaptive=true,dCurrent=null,dInputs=null,dValidationId=null;
try{dConfig={...dConfig,...JSON.parse(localStorage.getItem('decap-config-v1')||'{}')};dHistory=JSON.parse(localStorage.getItem('decap-history-v1')||'[]');dCalibrations=JSON.parse(localStorage.getItem('decap-calibrations-v1')||'[]');dAdaptive=localStorage.getItem('decap-adaptive-enabled')!=='false'}catch{}
const dIds=['dTank1Height','dTank2Height','dCurrent','dTarget'];
const dSpecs=[['tank1CapacityLiters','Capacidade útil da caixa 1','L'],['tank1HeightCm','Altura útil da caixa 1','cm'],['tank2LengthM','Comprimento da caixa 2','m'],['tank2WidthM','Largura da caixa 2','m'],['tank2HeightCm','Profundidade da caixa 2','cm'],['minConcentrationPct','Concentração mínima','%'],['maxConcentrationPct','Concentração máxima','%']];
function dConfigUI(){$('dConfigFields').innerHTML=dSpecs.map(([k,l,u])=>`<label>${l}<input data-dconfig="${k}" type="number" min="0" step="0.01" value="${dConfig[k]}"> ${u}</label>`).join('');$('dTank1Hint').textContent=`Máximo ${dConfig.tank1HeightCm} cm · ${br(dConfig.tank1CapacityLiters,0)} L úteis`;$('dTank2Hint').textContent=`Máximo ${dConfig.tank2HeightCm} cm · ${br(dConfig.tank2LengthM*dConfig.tank2WidthM*dConfig.tank2HeightCm*10,0)} L`;document.querySelectorAll('[data-dconfig]').forEach(el=>el.oninput=e=>{dConfig[e.target.dataset.dconfig]=Number(e.target.value);localStorage.setItem('decap-config-v1',JSON.stringify(dConfig));dConfigUIHints();dCalculate()})}
function dConfigUIHints(){$('dTank1Hint').textContent=`Máximo ${dConfig.tank1HeightCm} cm · ${br(dConfig.tank1CapacityLiters,0)} L úteis`;$('dTank2Hint').textContent=`Máximo ${dConfig.tank2HeightCm} cm · ${br(dConfig.tank2LengthM*dConfig.tank2WidthM*dConfig.tank2HeightCm*10,0)} L`}
function dReadInputs(){return{tank1HeightCm:Number($('dTank1Height').value),tank2HeightCm:Number($('dTank2Height').value),currentConcentrationPct:Number($('dCurrent').value),targetConcentrationPct:Number($('dTarget').value)}}
function dCalculate(){if(!$('dTank1Height').value||!$('dTank2Height').value||!$('dCurrent').value){$('dEmpty').hidden=false;$('dOutput').hidden=true;dCurrent=null;return}const i=dReadInputs(),e=M.validatePicklingInputs(i,dConfig);$('dErrors').hidden=!e.length;$('dErrors').textContent=e.join(' ');if(e.length){$('dEmpty').hidden=false;$('dOutput').hidden=true;dCurrent=null;return}const stats=M.calibrationStats(dCalibrations),factor=dAdaptive?stats.appliedFactor:1;dInputs=i;dCurrent=M.calculatePicklingAll(i,dConfig,factor);$('dEmpty').hidden=true;$('dOutput').hidden=false;$('dTank1Volume').textContent=br(dCurrent.tank1VolumeLiters)+' L';$('dTank2Volume').textContent=br(dCurrent.tank2VolumeLiters)+' L';$('dTotalVolume').textContent=br(dCurrent.totalVolumeLiters)+' L';$('dModelConfidence').textContent=dAdaptive?stats.confidence:'APRENDIZADO DESATIVADO';$('dModelFactor').textContent=`Fator × ${factor.toFixed(4).replace('.',',')}`;$('dAlcoholDose').textContent=br(dCurrent.alcoholToAddLiters);$('dOperationalDose').textContent=br(dCurrent.operationalAlcoholLiters,0);const s=$('dStatus');s.className='status '+(dCurrent.status==='DENTRO DA FAIXA'?'ok':dCurrent.status==='ABAIXO DA FAIXA'?'low':'high');s.querySelector('strong').textContent=dCurrent.status;const water=dCurrent.status==='ACIMA DA FAIXA';$('dWaterBox').hidden=!water;if(water)$('dWaterDose').textContent=`${br(dCurrent.waterToAddLiters)} L para retornar ao limite máximo de ${br(dConfig.maxConcentrationPct,2)}%`}
dIds.forEach(id=>$(id).addEventListener('input',dCalculate));
$('dClear').onclick=()=>{dIds.forEach(id=>$(id).value=id==='dTarget'?'3.0':'');$('dMessage').textContent='';dCalculate()};
$('dResetConfig').onclick=()=>{dConfig={...M.DEFAULT_PICKLING_CONFIG};localStorage.setItem('decap-config-v1',JSON.stringify(dConfig));dConfigUI();dCalculate()};
$('dSave').onclick=()=>{if(!dCurrent)return;dHistory.unshift({...dInputs,...dCurrent,id:(crypto.randomUUID?crypto.randomUUID():Date.now().toString()),timestamp:new Date().toISOString()});dPersist();$('dMessage').textContent='Medição registrada no histórico da decapagem.'};
function dPersist(){localStorage.setItem('decap-history-v1',JSON.stringify(dHistory));localStorage.setItem('decap-calibrations-v1',JSON.stringify(dCalibrations));dRenderHistory();dCalculate()}
function dRenderHistory(){const stats=M.calibrationStats(dCalibrations);$('dCount').textContent=dHistory.length;$('dAdaptiveEnabled').checked=dAdaptive;$('dLearningSummary').textContent=stats.sampleCount?`${stats.sampleCount} validação(ões) · ${stats.confidence} · fator × ${stats.appliedFactor.toFixed(4).replace('.',',')}`:'Nenhuma validação pós-correção - usando o volume útil nominal';$('dNoHistory').hidden=!!dHistory.length;$('dHistoryBody').innerHTML=dHistory.map(i=>{const c=dCalibrations.find(x=>x.recordId===i.id);return`<tr><td>${new Date(i.timestamp).toLocaleString('pt-BR')}</td><td>Caixa 1 ${br(i.tank1HeightCm)} · Caixa 2 ${br(i.tank2HeightCm)}</td><td>${br(i.currentConcentrationPct,2)}%</td><td>${br(i.totalVolumeLiters)} L</td><td><span class="badge ${i.status==='DENTRO DA FAIXA'?'ok':i.status==='ABAIXO DA FAIXA'?'low':'high'}">${i.status}</span></td><td>${br(i.alcoholToAddLiters)} L (${br(i.operationalAlcoholLiters,0)} L op.)</td><td>${c?`<span class="validated">✓ ${br(c.afterConcentrationPct,2)}% · fator × ${c.factor.toFixed(4).replace('.',',')}</span>`:`<button class="validate" data-dvalidate="${i.id}">Validar resultado</button>`}</td><td><button class="delete" data-ddelete="${i.id}" title="Excluir">✕</button></td></tr>`}).join('');document.querySelectorAll('[data-ddelete]').forEach(b=>b.onclick=()=>{dHistory=dHistory.filter(i=>i.id!==b.dataset.ddelete);dCalibrations=dCalibrations.filter(c=>c.recordId!==b.dataset.ddelete);dPersist()});document.querySelectorAll('[data-dvalidate]').forEach(b=>b.onclick=()=>dOpenValidation(b.dataset.dvalidate))}
function dOpenValidation(id){const r=dHistory.find(i=>i.id===id);if(!r)return;dValidationId=id;$('dValidationRecord').textContent=`Medição inicial: ${br(r.currentConcentrationPct,2)}% · volume previsto ${br(r.totalVolumeLiters)} L`;$('dActualAlcohol').value=r.operationalAlcoholLiters||r.alcoholToAddLiters||'';$('dAfterConcentration').value='';$('dValidationError').hidden=true;$('dValidationDialog').showModal()}
$('dSaveValidation').onclick=()=>{const r=dHistory.find(i=>i.id===dValidationId),alcohol=Number($('dActualAlcohol').value),after=Number($('dAfterConcentration').value),observed=r&&M.inferObservedVolumeFromOil(alcohol,r.currentConcentrationPct,after);if(!r||!observed){$('dValidationError').hidden=false;$('dValidationError').textContent='A concentração final deve ser maior que a inicial e o álcool real deve ser maior que zero. Não valide se houve retirada de solução ou adição de água.';return}const geometric=r.geometricVolumeLiters||r.tank1VolumeLiters+r.tank2VolumeLiters,factor=observed/geometric;dCalibrations=dCalibrations.filter(c=>c.recordId!==r.id);dCalibrations.push({recordId:r.id,timestamp:new Date().toISOString(),actualAlcoholLiters:alcohol,beforeConcentrationPct:r.currentConcentrationPct,afterConcentrationPct:after,observedVolumeLiters:observed,geometricVolumeLiters:geometric,factor});dPersist();$('dValidationDialog').close()};
$('dAdaptiveEnabled').onchange=e=>{dAdaptive=e.target.checked;localStorage.setItem('decap-adaptive-enabled',String(dAdaptive));dPersist()};$('dResetLearning').onclick=()=>{if(confirm('Apagar todas as validações da decapagem?')){dCalibrations=[];dPersist()}};
let dTechnicalUnlocked=sessionStorage.getItem('decap-tech-unlocked')==='true';$('dTechnicalDetails').querySelector('summary').onclick=e=>{if(!dTechnicalUnlocked){e.preventDefault();const password=prompt('Digite a senha para acessar os parâmetros da decapagem:');if(password==='processo'){dTechnicalUnlocked=true;sessionStorage.setItem('decap-tech-unlocked','true');$('dTechnicalDetails').open=true}else if(password!==null)alert('Senha incorreta.')}};$('dLockConfig').onclick=()=>{dTechnicalUnlocked=false;sessionStorage.removeItem('decap-tech-unlocked');$('dTechnicalDetails').open=false};
document.querySelectorAll('[data-dtab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-dtab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.pickling-content.tabpage').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.dtab).classList.add('active')});
document.querySelectorAll('[data-system]').forEach(b=>b.onclick=()=>{const pickling=b.dataset.system==='pickling';document.querySelectorAll('[data-system]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.oil-content').forEach(x=>x.hidden=pickling);['calculo','historico','metodo'].forEach(id=>$(id).hidden=pickling);document.querySelectorAll('.pickling-content').forEach(x=>x.hidden=!pickling)});
$('dCsv').onclick=()=>{const h=['data_hora','altura_caixa_1_cm','altura_caixa_2_cm','concentracao_atual_pct','concentracao_alvo_pct','volume_caixa_1_l','volume_caixa_2_l','volume_total_l','fator_usado','status','alcool_teorico_l','alcool_operacional_l','agua_teorica_l','alcool_real_l','concentracao_apos_pct','volume_observado_l','fator_observado'];const rows=dHistory.map(i=>{const c=dCalibrations.find(x=>x.recordId===i.id)||{};return[i.timestamp,i.tank1HeightCm,i.tank2HeightCm,i.currentConcentrationPct,i.targetConcentrationPct,i.tank1VolumeLiters,i.tank2VolumeLiters,i.totalVolumeLiters,i.calibrationFactor||1,i.status,i.alcoholToAddLiters,i.operationalAlcoholLiters,i.waterToAddLiters,c.actualAlcoholLiters||'',c.afterConcentrationPct||'',c.observedVolumeLiters||'',c.factor||'']});download('historico_decapagem.csv','\uFEFF'+[h,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\r\n'),'text/csv;charset=utf-8')};
$('dBackup').onclick=()=>download('backup_decapagem.json',JSON.stringify({version:1,config:dConfig,history:dHistory,calibrations:dCalibrations,adaptiveEnabled:dAdaptive},null,2),'application/json');$('dImport').onclick=()=>$('dFile').click();$('dFile').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(d.version!==1||!Array.isArray(d.history))throw 0;dConfig={...M.DEFAULT_PICKLING_CONFIG,...d.config};dHistory=d.history;dCalibrations=Array.isArray(d.calibrations)?d.calibrations:[];dAdaptive=d.adaptiveEnabled!==false;localStorage.setItem('decap-config-v1',JSON.stringify(dConfig));dPersist();dConfigUI();alert('Backup da decapagem importado.')}catch{alert('Arquivo de backup da decapagem inválido.')}};
configUI();renderHistory();calculate();dConfigUI();dRenderHistory();dCalculate();
})();
